name: Punish
author: JRoy
version: 1.0
api-version: 1.14
main: io.github.jroy.punish.Punish
commands:
  punish:
    description: Punishment Command
    usage: /punish
    aliases: p
  punishhistory:
    description: Punishment History Command
    usage: /punishhistory
    aliases: ph
  addcache:
    description: Adds name to uuid cache
    usage: /addcache